import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType, PageBreak, ImageRun } from "docx";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { dataUrlToUint8Array } from "./chartImageRenderer";
import { getTableLabel, getFigureLabel, generateTableInterpretation, generateFigureInterpretation, getDescriptiveHeaders } from "./academicFormatter";
import type { AnalysisResultItem } from "./statsEngine";
import { stripLatex } from "./latexSanitizer";

export interface ChartImage {
  title: string;
  dataUrl: string;
  width: number;
  height: number;
  chartType?: string;
  chartData?: { name?: string; value?: number; x?: number; y?: number }[];
}

export interface ExportData {
  projectTitle: string;
  projectType: string;
  projectDomain: string;
  projectDescription: string;
  level: string;
  lang: string;
  university?: string;
  department?: string;
  author?: string;
  statsTable: { variable: string; n: number; mean: number; std: number; min: number; max: number }[];
  testResults: { label: string; value: string }[];
  interpretation: string;
  conclusion: string;
  recommendations: string;
  chartImages?: ChartImage[];
  analysisResults?: AnalysisResultItem[];
  // Academic metadata
  objective?: string;
  specificObjectives?: string[];
  studyType?: string;
  studyDesign?: string;
  population?: string;
  primaryVariable?: string;
  hypothesis?: string;
  advancedHypothesis?: string;
  independentVars?: string;
  dependentVar?: string;
  controlVars?: string;
  mediatorVars?: string;
  moderatorVars?: string;
  conceptualModel?: string;
}

type ExportContent = "full" | "results" | "graphs" | "interpretation" | "conclusion";

const labels: Record<string, Record<string, string>> = {
  fr: {
    fullReport: "Rapport d'Analyse Complet",
    projectInfo: "Informations du Projet",
    title: "Titre du projet",
    level: "Niveau d'étude",
    domain: "Domaine de recherche",
    type: "Type de projet",
    description: "Description",
    statsResults: "Résultats Statistiques",
    descriptiveStats: "Statistiques Descriptives",
    testResults: "Résultats des Tests",
    variable: "Variable",
    mean: "Moyenne",
    std: "Écart-type",
    interpretation: "Interprétation Académique",
    conclusion: "Conclusion",
    recommendations: "Recommandations",
    generatedBy: "Généré par Dr Data 2.0 — Assistant Joël",
    noData: "Les données seront disponibles après l'analyse.",
    charts: "Graphiques",
    studyObjectives: "Objectifs de l'étude",
    methodology: "Méthodologie",
    generalObjective: "Objectif général",
    specificObjectives: "Objectifs spécifiques",
    studyType: "Type d'étude",
    studyDesign: "Devis de recherche",
    population: "Population d'étude",
    primaryVariable: "Variable principale",
    hypothesis: "Hypothèse",
    advancedHypothesis: "Hypothèse avancée",
    independentVars: "Variables indépendantes",
    dependentVar: "Variable dépendante",
    controlVars: "Variables de contrôle",
    mediatorVars: "Variables médiatrices",
    moderatorVars: "Variables modératrices",
    conceptualModel: "Modèle conceptuel",
  },
  en: {
    fullReport: "Full Analysis Report",
    projectInfo: "Project Information",
    title: "Project Title",
    level: "Study Level",
    domain: "Research Domain",
    type: "Project Type",
    description: "Description",
    statsResults: "Statistical Results",
    descriptiveStats: "Descriptive Statistics",
    testResults: "Test Results",
    variable: "Variable",
    mean: "Mean",
    std: "Std. Dev.",
    interpretation: "Academic Interpretation",
    conclusion: "Conclusion",
    recommendations: "Recommendations",
    generatedBy: "Generated by Dr Data 2.0 — Assistant Joël",
    noData: "Data will be available after analysis.",
    charts: "Charts",
    studyObjectives: "Study Objectives",
    methodology: "Methodology",
    generalObjective: "General Objective",
    specificObjectives: "Specific Objectives",
    studyType: "Study Type",
    studyDesign: "Study Design",
    population: "Study Population",
    primaryVariable: "Primary Variable",
    hypothesis: "Hypothesis",
    advancedHypothesis: "Advanced Hypothesis",
    independentVars: "Independent Variables",
    dependentVar: "Dependent Variable",
    controlVars: "Control Variables",
    mediatorVars: "Mediator Variables",
    moderatorVars: "Moderator Variables",
    conceptualModel: "Conceptual Model",
  },
  es: {
    fullReport: "Informe de Análisis Completo",
    projectInfo: "Información del Proyecto",
    title: "Título del proyecto",
    level: "Nivel de estudio",
    domain: "Dominio de investigación",
    type: "Tipo de proyecto",
    description: "Descripción",
    statsResults: "Resultados Estadísticos",
    descriptiveStats: "Estadísticas Descriptivas",
    testResults: "Resultados de Pruebas",
    variable: "Variable",
    mean: "Media",
    std: "Desv. Est.",
    interpretation: "Interpretación Académica",
    conclusion: "Conclusión",
    recommendations: "Recomendaciones",
    generatedBy: "Generado por Dr Data 2.0 — Asistente Joël",
    noData: "Los datos estarán disponibles después del análisis.",
    charts: "Gráficos",
    studyObjectives: "Objetivos del estudio",
    methodology: "Metodología",
    generalObjective: "Objetivo general",
    specificObjectives: "Objetivos específicos",
    studyType: "Tipo de estudio",
    studyDesign: "Diseño del estudio",
    population: "Población de estudio",
    primaryVariable: "Variable principal",
    hypothesis: "Hipótesis",
    advancedHypothesis: "Hipótesis avanzada",
    independentVars: "Variables independientes",
    dependentVar: "Variable dependiente",
    controlVars: "Variables de control",
    mediatorVars: "Variables mediadoras",
    moderatorVars: "Variables moderadoras",
    conceptualModel: "Modelo conceptual",
  },
  de: {
    fullReport: "Vollständiger Analysebericht",
    projectInfo: "Projektinformationen",
    title: "Projekttitel",
    level: "Studienstufe",
    domain: "Forschungsbereich",
    type: "Projekttyp",
    description: "Beschreibung",
    statsResults: "Statistische Ergebnisse",
    descriptiveStats: "Deskriptive Statistik",
    testResults: "Testergebnisse",
    variable: "Variable",
    mean: "Mittelwert",
    std: "Std. Abw.",
    interpretation: "Akademische Interpretation",
    conclusion: "Schlussfolgerung",
    recommendations: "Empfehlungen",
    generatedBy: "Erstellt mit Dr Data 2.0 — Assistent Joël",
    noData: "Daten werden nach der Analyse verfügbar sein.",
    charts: "Diagramme",
    studyObjectives: "Studienziele",
    methodology: "Methodik",
    generalObjective: "Allgemeines Ziel",
    specificObjectives: "Spezifische Ziele",
    studyType: "Studientyp",
    studyDesign: "Studiendesign",
    population: "Studienpopulation",
    primaryVariable: "Hauptvariable",
    hypothesis: "Hypothese",
    advancedHypothesis: "Erweiterte Hypothese",
    independentVars: "Unabhängige Variablen",
    dependentVar: "Abhängige Variable",
    controlVars: "Kontrollvariablen",
    mediatorVars: "Mediatorvariablen",
    moderatorVars: "Moderatorvariablen",
    conceptualModel: "Konzeptmodell",
  },
  pt: {
    fullReport: "Relatório de Análise Completo",
    projectInfo: "Informações do Projeto",
    title: "Título do projeto",
    level: "Nível de estudo",
    domain: "Domínio de pesquisa",
    type: "Tipo de projeto",
    description: "Descrição",
    statsResults: "Resultados Estatísticos",
    descriptiveStats: "Estatísticas Descritivas",
    testResults: "Resultados dos Testes",
    variable: "Variável",
    mean: "Média",
    std: "Desvio Padrão",
    interpretation: "Interpretação Acadêmica",
    conclusion: "Conclusão",
    recommendations: "Recomendações",
    generatedBy: "Gerado por Dr Data 2.0 — Assistente Joël",
    noData: "Os dados estarão disponíveis após a análise.",
    charts: "Gráficos",
    studyObjectives: "Objetivos do estudo",
    methodology: "Metodologia",
    generalObjective: "Objetivo geral",
    specificObjectives: "Objetivos específicos",
    studyType: "Tipo de estudo",
    studyDesign: "Desenho do estudo",
    population: "População de estudo",
    primaryVariable: "Variável principal",
    hypothesis: "Hipótese",
    advancedHypothesis: "Hipótese avançada",
    independentVars: "Variáveis independentes",
    dependentVar: "Variável dependente",
    controlVars: "Variáveis de controle",
    mediatorVars: "Variáveis mediadoras",
    moderatorVars: "Variáveis moderadoras",
    conceptualModel: "Modelo conceitual",
  },
};

function l(lang: string): Record<string, string> {
  return labels[lang] || labels.en;
}

function levelLabel(level: string, lang: string): string {
  const map: Record<string, Record<string, string>> = {
    fr: { student_license: "Licence", student_master: "Master", student_doctorat: "Doctorat" },
    en: { student_license: "Bachelor", student_master: "Master", student_doctorat: "Doctorate" },
    es: { student_license: "Licenciatura", student_master: "Máster", student_doctorat: "Doctorado" },
    de: { student_license: "Bachelor", student_master: "Master", student_doctorat: "Doktorat" },
    pt: { student_license: "Licenciatura", student_master: "Mestrado", student_doctorat: "Doutorado" },
  };
  return (map[lang] || map.en)[level] || level;
}

function filePrefix(level: string): string {
  if (level.includes("master")) return "Master";
  if (level.includes("doctorat")) return "Doctorate";
  return "Licence";
}

// ─── DOCX Export ───

export async function exportDocx(data: ExportData, content: ExportContent) {
  const t = l(data.lang);
  const sections: (Paragraph | Table)[] = [];

  const addHeading = (text: string, headingLevel: (typeof HeadingLevel)[keyof typeof HeadingLevel] = HeadingLevel.HEADING_1) =>
    sections.push(new Paragraph({ heading: headingLevel, children: [new TextRun({ text, bold: true })] }));

  const addText = (text: string) =>
    sections.push(new Paragraph({ children: [new TextRun(text)], spacing: { after: 120 } }));

  const addField = (label: string, value: string) =>
    sections.push(new Paragraph({
      children: [new TextRun({ text: `${label}: `, bold: true }), new TextRun(value)],
      spacing: { after: 80 },
    }));

  // Title page
  sections.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 2400, after: 400 },
    children: [new TextRun({ text: t.fullReport, bold: true, size: 48 })],
  }));
  sections.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: data.projectTitle, size: 32 })],
    spacing: { after: 200 },
  }));
  sections.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: t.generatedBy, size: 20, italics: true, color: "666666" })],
    spacing: { after: 600 },
  }));
  sections.push(new Paragraph({ children: [new PageBreak()] }));

  // Project Info
  if (content === "full" || content === "results") {
    addHeading(t.projectInfo);
    addField(t.title, data.projectTitle);
    addField(t.level, levelLabel(data.level, data.lang));
    addField(t.type, data.projectType);
    addField(t.domain, data.projectDomain);
    if (data.projectDescription) addField(t.description, data.projectDescription);
    if (data.population) addField(t.population, data.population);
    if (data.primaryVariable) addField(t.primaryVariable, data.primaryVariable);
    sections.push(new Paragraph({ children: [] }));

    // Study Objectives
    const hasObjectives = data.objective || (data.specificObjectives && data.specificObjectives.length > 0);
    if (hasObjectives) {
      addHeading(t.studyObjectives, HeadingLevel.HEADING_2);
      if (data.objective) addField(t.generalObjective, data.objective);
      if (data.specificObjectives && data.specificObjectives.length > 0) {
        sections.push(new Paragraph({
          children: [new TextRun({ text: `${t.specificObjectives}:`, bold: true })],
          spacing: { after: 40 },
        }));
        data.specificObjectives.forEach((obj, i) => {
          sections.push(new Paragraph({
            children: [new TextRun(`${i + 1}. ${obj}`)],
            spacing: { after: 40 },
            indent: { left: 360 },
          }));
        });
      }
      sections.push(new Paragraph({ children: [] }));
    }

    // Methodology
    const hasMethodology = data.studyType || data.studyDesign || data.hypothesis || data.independentVars || data.dependentVar;
    if (hasMethodology) {
      addHeading(t.methodology, HeadingLevel.HEADING_2);
      if (data.studyType) addField(t.studyType, data.studyType);
      if (data.studyDesign) addField(t.studyDesign, data.studyDesign);
      if (data.hypothesis) addField(t.hypothesis, data.hypothesis);
      if (data.advancedHypothesis) addField(t.advancedHypothesis, data.advancedHypothesis);
      if (data.independentVars) addField(t.independentVars, data.independentVars);
      if (data.dependentVar) addField(t.dependentVar, data.dependentVar);
      if (data.controlVars) addField(t.controlVars, data.controlVars);
      if (data.mediatorVars) addField(t.mediatorVars, data.mediatorVars);
      if (data.moderatorVars) addField(t.moderatorVars, data.moderatorVars);
      if (data.conceptualModel) addField(t.conceptualModel, data.conceptualModel);
      sections.push(new Paragraph({ children: [] }));
    }
  }

  // Stats tables with academic formatting
  if (content === "full" || content === "results") {
    const tableLabel = getTableLabel(data.lang);
    
    let tableNum = 1;

    addHeading(t.statsResults);

    // Descriptive stats table
    if (data.statsTable.length > 0) {
      // Academic table title
      sections.push(new Paragraph({
        spacing: { before: 200, after: 80 },
        children: [
          new TextRun({ text: `${tableLabel} ${tableNum}: `, bold: true, size: 22 }),
          new TextRun({ text: t.descriptiveStats, bold: true, size: 22 }),
        ],
      }));

      const cellBorder = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
      const borders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder };
      const headers = [t.variable, "N", t.mean, t.std, "Min", "Max"];
      const headerRow = new TableRow({
        children: headers.map(h => new TableCell({
          borders,
          shading: { fill: "2563EB", type: ShadingType.CLEAR },
          width: { size: 1560, type: WidthType.DXA },
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })],
        })),
      });
      const dataRows = data.statsTable.map(row => new TableRow({
        children: [row.variable, String(row.n), String(row.mean), String(row.std), String(row.min), String(row.max)].map(v =>
          new TableCell({
            borders,
            width: { size: 1560, type: WidthType.DXA },
            children: [new Paragraph({ children: [new TextRun({ text: v, size: 20 })] })],
          })
        ),
      }));

      sections.push(new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [1560, 1560, 1560, 1560, 1560, 1560],
        rows: [headerRow, ...dataRows],
      }));

      // Source
      sections.push(new Paragraph({
        spacing: { before: 60, after: 40 },
      }));

      // Interpretation for descriptive stats
      if (data.analysisResults) {
        const descResult = data.analysisResults.find(r => r.descriptive && r.descriptive.length > 0);
        if (descResult) {
          const interp = generateTableInterpretation(descResult, data.lang, data.level);
          if (interp) {
            sections.push(new Paragraph({
              spacing: { before: 40, after: 120 },
              children: [
                new TextRun({ text: t.interpretation + ": ", bold: true, italics: true, size: 20 }),
                new TextRun({ text: interp, italics: true, size: 20 }),
              ],
            }));
          }
        }
      }

      tableNum++;
      sections.push(new Paragraph({ children: [] }));
    }

    // Test results table with academic numbering
    if (data.testResults.length > 0) {
      sections.push(new Paragraph({
        spacing: { before: 200, after: 80 },
        children: [
          new TextRun({ text: `${tableLabel} ${tableNum}: `, bold: true, size: 22 }),
          new TextRun({ text: t.testResults, bold: true, size: 22 }),
        ],
      }));

      const cellBorder = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
      const borders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder };
      const headerRow = new TableRow({
        children: ["Test", t.variable.charAt(0).toUpperCase() + t.variable.slice(1)].map(h => new TableCell({
          borders,
          shading: { fill: "2563EB", type: ShadingType.CLEAR },
          width: { size: 4680, type: WidthType.DXA },
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })],
        })),
      });
      const testRows = data.testResults.map(r => new TableRow({
        children: [r.label, r.value].map(v => new TableCell({
          borders,
          width: { size: 4680, type: WidthType.DXA },
          children: [new Paragraph({ children: [new TextRun({ text: v, size: 20 })] })],
        })),
      }));

      sections.push(new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [4680, 4680],
        rows: [headerRow, ...testRows],
      }));

      // Source
      sections.push(new Paragraph({
        spacing: { before: 60, after: 120 },
      }));

      tableNum++;
      sections.push(new Paragraph({ children: [] }));
    }
  }

  // Charts with academic formatting
  if ((content === "full" || content === "results") && data.chartImages && data.chartImages.length > 0) {
    const figLabel = getFigureLabel(data.lang);
    
    addHeading(t.charts, HeadingLevel.HEADING_2);

    for (let i = 0; i < data.chartImages.length; i++) {
      const chart = data.chartImages[i];
      const figNum = i + 1;

      // Academic figure title
      sections.push(new Paragraph({
        spacing: { before: 200, after: 80 },
        children: [
          new TextRun({ text: `${figLabel} ${figNum}: `, bold: true, size: 22 }),
          new TextRun({ text: chart.title, bold: true, size: 22 }),
        ],
      }));

      // Chart image
      try {
        const imgData = dataUrlToUint8Array(chart.dataUrl);
        sections.push(new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new ImageRun({
            type: "png",
            data: imgData,
            transformation: { width: chart.width, height: chart.height },
            altText: { title: chart.title, description: chart.title, name: chart.title },
          })],
        }));
      } catch {
        // Skip chart if image fails
      }

      // Source
      sections.push(new Paragraph({
        spacing: { before: 60, after: 40 },
      }));

      // Figure interpretation
      if (chart.chartType && chart.chartData) {
        const figInterp = generateFigureInterpretation(chart.chartType, chart.title, chart.chartData, data.lang);
        if (figInterp) {
          sections.push(new Paragraph({
            spacing: { before: 40, after: 120 },
            children: [
              new TextRun({ text: t.interpretation + ": ", bold: true, italics: true, size: 20 }),
              new TextRun({ text: figInterp, italics: true, size: 20 }),
            ],
          }));
        }
      }

      sections.push(new Paragraph({ children: [] }));
    }
  }

  // Interpretation
  if (content === "full" || content === "interpretation") {
    addHeading(t.interpretation);
    addText(stripLatex(data.interpretation || t.noData));
    sections.push(new Paragraph({ children: [] }));
  }

  // Conclusion
  if (content === "full" || content === "conclusion") {
    addHeading(t.conclusion);
    addText(data.conclusion || t.noData);
    sections.push(new Paragraph({ children: [] }));
    addHeading(t.recommendations);
    addText(data.recommendations || t.noData);
  }

  const doc = new Document({
    styles: {
      default: { document: { run: { font: "Arial", size: 24 } } },
    },
    sections: [{ children: sections }],
  });

  const buffer = await Packer.toBlob(doc);
  const prefix = filePrefix(data.level);
  const contentSuffix = content === "full" ? "Analysis_Report" : content === "results" ? "Statistical_Results" : content === "interpretation" ? "Interpretation" : "Conclusion";
  saveAs(buffer, `${prefix}_${contentSuffix}.docx`);
}

// ─── PDF Export ───

export function exportPdf(data: ExportData, content: ExportContent) {
  const t = l(data.lang);
  const doc = new jsPDF();
  let y = 20;

  const addTitle = (text: string) => {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(text, 105, y, { align: "center" });
    y += 12;
  };

  const addH2 = (text: string) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(text, 14, y);
    y += 8;
  };

  const addBody = (text: string) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, 180);
    doc.text(lines, 14, y);
    y += lines.length * 6 + 4;
  };

  const addFieldPdf = (label: string, value: string) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`${label}: `, 14, y);
    const labelW = doc.getTextWidth(`${label}: `);
    doc.setFont("helvetica", "normal");
    doc.text(value, 14 + labelW, y);
    y += 7;
  };

  // Title
  addTitle(t.fullReport);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(data.projectTitle, 105, y, { align: "center" });
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(t.generatedBy, 105, y, { align: "center" });
  doc.setTextColor(0);
  y += 16;

  if (content === "full" || content === "results") {
    addH2(t.projectInfo);
    addFieldPdf(t.title, data.projectTitle);
    addFieldPdf(t.level, levelLabel(data.level, data.lang));
    addFieldPdf(t.type, data.projectType);
    addFieldPdf(t.domain, data.projectDomain);
    if (data.projectDescription) addFieldPdf(t.description, data.projectDescription);
    if (data.population) addFieldPdf(t.population, data.population);
    if (data.primaryVariable) addFieldPdf(t.primaryVariable, data.primaryVariable);
    y += 4;

    // Study Objectives
    if (data.objective || (data.specificObjectives && data.specificObjectives.length > 0)) {
      addH2(t.studyObjectives);
      if (data.objective) addFieldPdf(t.generalObjective, data.objective);
      if (data.specificObjectives && data.specificObjectives.length > 0) {
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(`${t.specificObjectives}:`, 14, y);
        y += 6;
        doc.setFont("helvetica", "normal");
        data.specificObjectives.forEach((obj, i) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(`${i + 1}. ${obj}`, 20, y);
          y += 6;
        });
      }
      y += 4;
    }

    // Methodology
    if (data.studyType || data.studyDesign || data.hypothesis || data.independentVars || data.dependentVar) {
      addH2(t.methodology);
      if (data.studyType) addFieldPdf(t.studyType, data.studyType);
      if (data.studyDesign) addFieldPdf(t.studyDesign, data.studyDesign);
      if (data.hypothesis) addFieldPdf(t.hypothesis, data.hypothesis);
      if (data.advancedHypothesis) addFieldPdf(t.advancedHypothesis, data.advancedHypothesis);
      if (data.independentVars) addFieldPdf(t.independentVars, data.independentVars);
      if (data.dependentVar) addFieldPdf(t.dependentVar, data.dependentVar);
      if (data.controlVars) addFieldPdf(t.controlVars, data.controlVars);
      if (data.mediatorVars) addFieldPdf(t.mediatorVars, data.mediatorVars);
      if (data.moderatorVars) addFieldPdf(t.moderatorVars, data.moderatorVars);
      if (data.conceptualModel) addFieldPdf(t.conceptualModel, data.conceptualModel);
      y += 4;
    }
    y += 2;

    addH2(t.descriptiveStats);

    const tableLabel = getTableLabel(data.lang);
    
    let tableNum = 1;

    // Academic table title
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`${tableLabel} ${tableNum}: ${t.descriptiveStats}`, 14, y);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [[t.variable, "N", t.mean, t.std, "Min", "Max"]],
      body: data.statsTable.map(r => [r.variable, r.n, r.mean, r.std, r.min, r.max]),
      theme: "grid",
      headStyles: { fillColor: [37, 99, 235] },
      margin: { left: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 4;

    // Source
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100);
    doc.setTextColor(0);
    y += 5;

    // Interpretation
    if (data.analysisResults) {
      const descResult = data.analysisResults.find(r => r.descriptive && r.descriptive.length > 0);
      if (descResult) {
        const interp = generateTableInterpretation(descResult, data.lang, data.level);
        if (interp) {
          if (y > 250) { doc.addPage(); y = 20; }
          doc.setFontSize(9);
          doc.setFont("helvetica", "italic");
          const interpLines = doc.splitTextToSize(interp, 180);
          doc.text(interpLines, 14, y);
          y += interpLines.length * 5 + 4;
        }
      }
    }
    doc.setFont("helvetica", "normal");
    tableNum++;
    y += 4;

    addH2(t.testResults);

    // Academic table title for test results
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`${tableLabel} ${tableNum}: ${t.testResults}`, 14, y);
    y += 6;

    autoTable(doc, {
      startY: y,
      head: [["Test", t.variable]],
      body: data.testResults.map(r => [r.label, r.value]),
      theme: "grid",
      headStyles: { fillColor: [37, 99, 235] },
      margin: { left: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 4;

    // Source
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100);
    doc.setTextColor(0);
    y += 8;
    doc.setFont("helvetica", "normal");
  }

  // Charts in PDF with academic formatting
  if ((content === "full" || content === "results") && data.chartImages && data.chartImages.length > 0) {
    const figLabel = getFigureLabel(data.lang);
    
    addH2(t.charts);

    for (let i = 0; i < data.chartImages.length; i++) {
      const chart = data.chartImages[i];
      const figNum = i + 1;

      if (y > 160) { doc.addPage(); y = 20; }

      // Academic figure title
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      const figTitle = `${figLabel} ${figNum}: ${chart.title}`;
      const titleText = figTitle.length > 80 ? figTitle.slice(0, 77) + "…" : figTitle;
      doc.text(titleText, 14, y);
      y += 5;

      // Chart image
      try {
        const imgW = 170;
        const imgH = (chart.height / chart.width) * imgW;
        doc.addImage(chart.dataUrl, "PNG", 14, y, imgW, imgH);
        y += imgH + 4;
      } catch {
        y += 4;
      }

      // Source
      doc.setFontSize(8);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(100);
      doc.setTextColor(0);
      y += 5;

      // Figure interpretation
      if (chart.chartType && chart.chartData) {
        const figInterp = generateFigureInterpretation(chart.chartType, chart.title, chart.chartData, data.lang);
        if (figInterp) {
          doc.setFontSize(9);
          doc.setFont("helvetica", "italic");
          const interpLines = doc.splitTextToSize(figInterp, 180);
          doc.text(interpLines, 14, y);
          y += interpLines.length * 5 + 4;
        }
      }

      doc.setFont("helvetica", "normal");
      y += 4;
    }
  }

  if (content === "full" || content === "interpretation") {
    addH2(t.interpretation);
    addBody(stripLatex(data.interpretation || t.noData));
  }

  if (content === "full" || content === "conclusion") {
    addH2(t.conclusion);
    addBody(data.conclusion || t.noData);
    addH2(t.recommendations);
    addBody(data.recommendations || t.noData);
  }

  const prefix = filePrefix(data.level);
  const contentSuffix = content === "full" ? "Analysis_Report" : content === "results" ? "Statistical_Results" : content === "interpretation" ? "Interpretation" : "Conclusion";
  doc.save(`${prefix}_${contentSuffix}.pdf`);
}

// ─── XLSX Export ───

export function exportXlsx(data: ExportData, content: ExportContent) {
  const t = l(data.lang);
  const wb = XLSX.utils.book_new();

  if (content === "full" || content === "results") {
    const infoData: (string | undefined)[][] = [
      [t.projectInfo, ""],
      [t.title, data.projectTitle],
      [t.level, levelLabel(data.level, data.lang)],
      [t.type, data.projectType],
      [t.domain, data.projectDomain],
      [t.description, data.projectDescription],
    ];
    if (data.population) infoData.push([t.population, data.population]);
    if (data.primaryVariable) infoData.push([t.primaryVariable, data.primaryVariable]);
    if (data.objective) infoData.push([], [t.studyObjectives, ""], [t.generalObjective, data.objective]);
    if (data.specificObjectives?.length) {
      infoData.push([t.specificObjectives, ""]);
      data.specificObjectives.forEach((o, i) => infoData.push([`  ${i + 1}.`, o]));
    }
    if (data.studyType || data.hypothesis || data.independentVars) {
      infoData.push([], [t.methodology, ""]);
      if (data.studyType) infoData.push([t.studyType, data.studyType]);
      if (data.studyDesign) infoData.push([t.studyDesign, data.studyDesign]);
      if (data.hypothesis) infoData.push([t.hypothesis, data.hypothesis]);
      if (data.advancedHypothesis) infoData.push([t.advancedHypothesis, data.advancedHypothesis]);
      if (data.independentVars) infoData.push([t.independentVars, data.independentVars]);
      if (data.dependentVar) infoData.push([t.dependentVar, data.dependentVar]);
      if (data.controlVars) infoData.push([t.controlVars, data.controlVars]);
      if (data.mediatorVars) infoData.push([t.mediatorVars, data.mediatorVars]);
      if (data.moderatorVars) infoData.push([t.moderatorVars, data.moderatorVars]);
      if (data.conceptualModel) infoData.push([t.conceptualModel, data.conceptualModel]);
    }
    const infoSheet = XLSX.utils.aoa_to_sheet(infoData);
    infoSheet["!cols"] = [{ wch: 30 }, { wch: 60 }];
    XLSX.utils.book_append_sheet(wb, infoSheet, t.projectInfo.substring(0, 31));

    const statsData = [
      [t.variable, "N", t.mean, t.std, "Min", "Max"],
      ...data.statsTable.map(r => [r.variable, r.n, r.mean, r.std, r.min, r.max]),
    ];
    const statsSheet = XLSX.utils.aoa_to_sheet(statsData);
    statsSheet["!cols"] = [{ wch: 15 }, { wch: 8 }, { wch: 12 }, { wch: 12 }, { wch: 10 }, { wch: 10 }];
    XLSX.utils.book_append_sheet(wb, statsSheet, t.descriptiveStats.substring(0, 31));

    const testData = [[t.testResults, ""], ...data.testResults.map(r => [r.label, r.value])];
    const testSheet = XLSX.utils.aoa_to_sheet(testData);
    testSheet["!cols"] = [{ wch: 20 }, { wch: 15 }];
    XLSX.utils.book_append_sheet(wb, testSheet, t.testResults.substring(0, 31));
  }

  if (content === "full" || content === "interpretation") {
    const intSheet = XLSX.utils.aoa_to_sheet([[t.interpretation], [stripLatex(data.interpretation || t.noData)]]);
    intSheet["!cols"] = [{ wch: 80 }];
    XLSX.utils.book_append_sheet(wb, intSheet, t.interpretation.substring(0, 31));
  }

  if (content === "full" || content === "conclusion") {
    const concSheet = XLSX.utils.aoa_to_sheet([
      [t.conclusion], [data.conclusion || t.noData],
      [], [t.recommendations], [data.recommendations || t.noData],
    ]);
    concSheet["!cols"] = [{ wch: 80 }];
    XLSX.utils.book_append_sheet(wb, concSheet, t.conclusion.substring(0, 31));
  }

  const prefix = filePrefix(data.level);
  const contentSuffix = content === "full" ? "Analysis_Report" : content === "results" ? "Statistical_Results" : content === "interpretation" ? "Interpretation" : "Conclusion";
  XLSX.writeFile(wb, `${prefix}_${contentSuffix}.xlsx`);
}
